; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28315.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\emad\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
